title_name = "Burnout Paradise"
title_id = "45410806"
hash = "0CC027FC408913C2"
media_id = "00000000"

[[patch]]
    name = "Burnout Paradise Breaker Island Artist Online"
    author = "JeBobs"
    is_enabled = true

    [[patch.string]]
        address = 0x82086ED8
        value = "gameserver.bo98.uk"

    [[patch.be8]]
        address = 0x82086EEA
        value = 0x00

    [[patch.string]]
        address = 0x82086EF8
        value = "gameserver.bo98.uk"
    
    [[patch.be8]]
        address = 0x82086F0A
        value = 0x00

    [[patch.string]]
        address = 0x82086F30
        value = "gameserver.bo98.uk"

    [[patch.be8]]
        address = 0x82086F42
        value = 0x00

    # Misc / Set Server String
    [[patch.string]]
        address = 0x82086C68
        value = 'Bo98 Gameserver'